title: Stack Problems from a Dev Guy
description: My Personal Developer Journey
author: Martin Patino
github: https://github.com/mpatino117
about: I am developer. Currently doing more in frontned, focused in Python, Node and loving Vue
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/thisguymartin"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/martin-patino-60b2b798"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/mpatino117"

share:
  twitter_username: thiguymartin
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: ""
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
